--------------------------------------------------------
--  File created - Thursday-February-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_USER
--------------------------------------------------------

  CREATE TABLE "ECOWATCHDB"."TBL_USER" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"FULL_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ECOWATCHDB.TBL_USER
SET DEFINE OFF;
Insert into ECOWATCHDB.TBL_USER (ID,EMAIL,PASSWORD,FULL_NAME) values (28,'armavicse@gmail.com','$2a$12$RXSkDlN9NVe3eozctcrG5.EwyV1cKnpMNcVz7uIEBOOhs8h8hNddS','Arunav');
--------------------------------------------------------
--  DDL for Index TBL_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOWATCHDB"."TBL_USER_PK" ON "ECOWATCHDB"."TBL_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_USER
--------------------------------------------------------

  ALTER TABLE "ECOWATCHDB"."TBL_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ECOWATCHDB"."TBL_USER" ADD CONSTRAINT "TBL_USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
