--------------------------------------------------------
--  File created - Thursday-February-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_DETECTION_REPORT
--------------------------------------------------------

  CREATE TABLE "ECOWATCHDB"."TBL_DETECTION_REPORT" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DETECTED_TEMP" VARCHAR2(100 BYTE), 
	"DETECTED_MQ2" VARCHAR2(100 BYTE), 
	"TIME" TIMESTAMP (6), 
	"DETECTED_STATUS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ECOWATCHDB.TBL_DETECTION_REPORT
SET DEFINE OFF;
Insert into ECOWATCHDB.TBL_DETECTION_REPORT (ID,DETECTED_TEMP,DETECTED_MQ2,TIME,DETECTED_STATUS) values (2,'28.2','228',to_timestamp('01-FEB-26 06.53.31.219000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'FIRE OR SMOKE');
Insert into ECOWATCHDB.TBL_DETECTION_REPORT (ID,DETECTED_TEMP,DETECTED_MQ2,TIME,DETECTED_STATUS) values (3,'28.9','252',to_timestamp('01-FEB-26 06.55.36.516000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'FIRE OR SMOKE');
--------------------------------------------------------
--  DDL for Index TBL_DETECTION_REPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOWATCHDB"."TBL_DETECTION_REPORT_PK" ON "ECOWATCHDB"."TBL_DETECTION_REPORT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_DETECTION_REPORT
--------------------------------------------------------

  ALTER TABLE "ECOWATCHDB"."TBL_DETECTION_REPORT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ECOWATCHDB"."TBL_DETECTION_REPORT" ADD CONSTRAINT "TBL_DETECTION_REPORT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
