--------------------------------------------------------
--  File created - Thursday-February-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_THRESHOLD
--------------------------------------------------------

  CREATE TABLE "ECOWATCHDB"."TBL_THRESHOLD" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"THRESH_TEMP" NUMBER, 
	"THRESH_MQ2" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ECOWATCHDB.TBL_THRESHOLD
SET DEFINE OFF;
Insert into ECOWATCHDB.TBL_THRESHOLD (ID,THRESH_TEMP,THRESH_MQ2) values (103,45,250);
Insert into ECOWATCHDB.TBL_THRESHOLD (ID,THRESH_TEMP,THRESH_MQ2) values (104,50,280);
--------------------------------------------------------
--  DDL for Index SYS_C008225
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOWATCHDB"."SYS_C008225" ON "ECOWATCHDB"."TBL_THRESHOLD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_THRESHOLD
--------------------------------------------------------

  ALTER TABLE "ECOWATCHDB"."TBL_THRESHOLD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ECOWATCHDB"."TBL_THRESHOLD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
